### ISSUE TITLE
completeMessage prop does not work

### ISSUE THREAD

**Issue by davidtom** [the-couch/rimp#1]
Hi, thanks for releasing this package - seems to be the best and easiest Mailchimp subscription library out there.

So far the only issue I've had is that the `completeMessage` prop is not working, and I always get the 'You’ve been added to our list.' message after submitting the form.

Looking at the package's code in my node_modules folder, it looks like the updates for 'allow for a configurable complete message' are not reflected on the package published on NPM.

I'm not too familiar with NPM publishing/updating, so this could be user error on my part. But just wanted to check in here to see if this has happened for anyone else and/or if there is a fix.

Thanks!

**Comment by iamkevingreen** [comment]
@davidtom Pushed an update to npm (@0.1.5), sorry about that! Also check out a more vanilla version here if you're interested: https://github.com/estrattonbailey/astrochimp

Planning on rewriting this to be less opinionated when I have time! ⌛️

**Comment by davidtom** [comment]
Wonderful, thank you!! I will also look into astrochimp as well, might be just what I need!
